### ISSUE TITLE
Shift Clicking Items going to right of inventory not first open slot.

### ISSUE THREAD

**Issue by whoshenry** [haveric/StackableItems#107]
Video: http://youtu.be/YwlfhA9Sng4  I am shift clicking with each click.

The items seem to go to the right of your inventory when shift clicking, only effecting Survival mode players. These players don't have access to Stackable Items, they are not listed under any groups in the config.

**Comment by haveric** [comment]
Because of the complexity of this plugin, there are a few situations where items are still affected by the stacking in StackableItems even though they do not have any items setup in the config for them.  I am trying to reduce that as much as possible, but it will take time.

With that said, I believe I have fixed this issue with the latest commits. I need to test it more before releasing it though as some of the changes may have adverse effects in other areas.

**Comment by whoshenry** [comment]
Great, look forward to the update!

**Comment by haveric** [comment]
Just uploaded v1.0.2 which fixes this and a bunch of other issues.
