### ISSUE TITLE
Hopelessly broken beyond 1.9

### ISSUE THREAD

**Issue by pquerner** [haveric/StackableItems#134]
I am running a private MC server which ran on 1.9 for a while, now I've updated to 1.14 to get all the new goodies (and we didnt play for a few years). 
This plugin is one of my favourites and sadly it doesnt work any more. 

I am currently in the process of debugging and partially fixing it, so it may "work" under 1.14 but its really a mess (as in I don't have a clue on how to fix most stuff and sometimes I don't even understand the sourcecode fully) and it will take some time.

This issue is just created in case someone steps in and knows how to easilly make it work beyond 1.9.

If you have any knowledge that could help me, its highly appreciated. Also, I only test "my use cases" so if there is some edge case I dont see right now, its helpful if you post here (with a Stacktrace if possible) and all the needed information.

**Comment by haveric** [comment]
This isn't too surprising as 1.13 caused a lot of breaking across plugins and 1.14 has added a new set of complexities. With that said, I don't think it would be too crazy to get StackableItems updated to 1.14, but with everything going on in real life, I have not had the time to get to updating this and as you've noticed there's a ton of work to do to get there. I have recently jumped back into plugin dev though and have been updating some of my smaller plugins to 1.14 as a starting step. This will likely be one of the last to get updated though just due to how much is going on.

As always, you are more than welcome to attempt to work on updating it and I welcome pull requests if it is of sufficient quality and would offer any support I can.

**Comment by pquerner** [comment]
Thanks for getting back. I would not expect for you to push it to 1.14 by yourself. (Being a free plugin and all) Currently I have it all in my private git and when I have something to show I'll PR it, of course.

**Comment by haveric** [comment]
New update just released (v.1.0.6) for 1.14

**Comment by pquerner** [comment]
Wow awesome! Have a beer or two on me. Kudos :)

**Comment by haveric** [comment]
Appreciate it, thanks!
